'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TrulyMail.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ActionPiano() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ActionPiano", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property activateButton_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("activateButton_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property add_icon_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_icon_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property add_icon_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_icon_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property add_icon_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_icon_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Addressbook_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Addressbook_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Addressbook_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Addressbook_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property AddUser_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AddUser_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property AddUser_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AddUser_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property AnimalsMouse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AnimalsMouse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Arrow_left_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arrow_left_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Arrow_right_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arrow_right_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;license version=&quot;1.1&quot;&gt;
        '''  &lt;Customer&gt;
        '''    &lt;name&gt;8729858
        '''(, )
        '''john@montgomerysoftware.com
        '''num:1&lt;/name&gt;
        '''  &lt;/Customer&gt;
        '''  &lt;products&gt;
        '''    &lt;Product&gt;
        '''      &lt;name&gt;aspNetEmail&lt;/name&gt;
        '''      &lt;version&gt;3&lt;/version&gt;
        '''      &lt;licensetype&gt;developer&lt;/licensetype&gt;
        '''      &lt;expires&gt;-1&lt;/expires&gt;
        '''    &lt;/Product&gt;
        '''  &lt;/products&gt;
        '''  &lt;LicenseInformation&gt;
        '''    &lt;Version&gt;1.1&lt;/Version&gt;
        '''    &lt;H1&gt;0&lt;/H1&gt;
        '''    &lt;H2&gt;k+HwV257DOIHndhV61fdCA==&lt;/H2&gt;
        '''  &lt;/LicenseInformation&gt;
        '''  &lt;Signature xmlns=&quot;http: [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property aspnetemail_xml_lic() As String
            Get
                Return ResourceManager.GetString("aspnetemail_xml_lic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;license version=&quot;1.1&quot;&gt;
        '''  &lt;Customer&gt;
        '''    &lt;name&gt;advancedintellect-4862
        '''(, )
        '''num:1&lt;/name&gt;
        '''  &lt;/Customer&gt;
        '''  &lt;products&gt;
        '''    &lt;Product&gt;
        '''      &lt;name&gt;aspNetMime&lt;/name&gt;
        '''      &lt;version&gt;2&lt;/version&gt;
        '''      &lt;licensetype&gt;developer&lt;/licensetype&gt;
        '''      &lt;expires&gt;-1&lt;/expires&gt;
        '''    &lt;/Product&gt;
        '''  &lt;/products&gt;
        '''  &lt;LicenseInformation&gt;
        '''    &lt;Version&gt;1.1&lt;/Version&gt;
        '''    &lt;H1&gt;0&lt;/H1&gt;
        '''    &lt;H2&gt;KHwhkA59+pXO+2JfU5M43g==&lt;/H2&gt;
        '''  &lt;/LicenseInformation&gt;
        '''  &lt;Signature xmlns=&quot;http://www.w3.org/20 [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property aspnetmime_xml_lic() As String
            Get
                Return ResourceManager.GetString("aspnetmime_xml_lic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;license version=&quot;1.1&quot;&gt;
        '''  &lt;Customer&gt;
        '''    &lt;name&gt;advancedintellect-4862
        '''(, )
        '''num:1&lt;/name&gt;
        '''  &lt;/Customer&gt;
        '''  &lt;products&gt;
        '''    &lt;Product&gt;
        '''      &lt;name&gt;aspNetPOP3&lt;/name&gt;
        '''      &lt;version&gt;2&lt;/version&gt;
        '''      &lt;licensetype&gt;developer&lt;/licensetype&gt;
        '''      &lt;expires&gt;-1&lt;/expires&gt;
        '''    &lt;/Product&gt;
        '''    &lt;Product&gt;
        '''      &lt;name&gt;aspNetMime&lt;/name&gt;
        '''      &lt;version&gt;2&lt;/version&gt;
        '''      &lt;licensetype&gt;developer&lt;/licensetype&gt;
        '''      &lt;expires&gt;-1&lt;/expires&gt;
        '''    &lt;/Product&gt;
        '''  &lt;/products&gt;
        '''  &lt;Licens [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property aspnetpop3_xml_lic() As String
            Get
                Return ResourceManager.GetString("aspnetpop3_xml_lic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Attach_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Attach_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Attach_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Attach_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property AutoText_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AutoText_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property AutoText_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AutoText_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property BallGreen_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BallGreen_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property BallRed_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BallRed_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property BallYellow_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BallYellow_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property BCC_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BCC_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property BCC_Hot_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BCC_Hot_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property BlueArrowDown_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BlueArrowDown_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property BlueArrowUp_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BlueArrowUp_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Bullets_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bullets_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Calendar_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Calendar_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Calendar_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Calendar_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property cancelButton_128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancelButton_128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CC_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CC_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CC_Hot_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CC_Hot_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Checkboxes_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Checkboxes_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Checkboxes_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Checkboxes_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CheckMark_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CheckMark_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CheckMark_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CheckMark_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property checkmark_trans_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checkmark_trans_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property clock_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clock_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property close_cold_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close_cold_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property close_hot_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close_hot_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Copy_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Copy_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Cut_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cut_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Deletemessage_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Deletemessage_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Deletemessage_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Deletemessage_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Download_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Download_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Download_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Download_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property download_trans_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download_trans_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property earth_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("earth_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property earth_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("earth_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Editmessage_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Editmessage_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Editmessage_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Editmessage_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Editpencil_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Editpencil_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Editpencil_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Editpencil_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property email_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("email_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property email_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("email_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Emptytrashcan_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Emptytrashcan_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Emptytrashcan_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Emptytrashcan_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi0\deflang1033\deflangfe1033\themelang1033\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f34\fbidi \froman\fcharset0\fprq2{\*\panose 02040503050406030204}Cambria Math;}
        '''{\f37\fbidi \fswiss\fcharset0\fprq2{\*\panose 020f0502020204030204}Calibri;}{\flomajor\f31500\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property EncryptionKeyRTF() As String
            Get
                Return ResourceManager.GetString("EncryptionKeyRTF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Erase_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Erase_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Erase_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Erase_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property erase_trans_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("erase_trans_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property FeelingsHeart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FeelingsHeart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property folder_closed_blue_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_closed_blue_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property folder_closed_green_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_closed_green_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property folder_closed_orange_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_closed_orange_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property folder_closed_purple_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_closed_purple_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property folder_closed_red_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_closed_red_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property folder_closed_yellow_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder_closed_yellow_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property FoodAvocado() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FoodAvocado", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Forward_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Forward_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Forward_3_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Forward_3_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Forward_3_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Forward_3_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Forward_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Forward_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Fulltrashcan_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fulltrashcan_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Fulltrashcan_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fulltrashcan_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Getmail_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Getmail_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Getmail_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Getmail_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Grid_240() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Grid_240", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Happy_20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Happy_20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property HighlightNothing_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HighlightNothing_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property HighlightNothing_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HighlightNothing_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property HighlightSender2_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HighlightSender2_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property HighlightSender2_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HighlightSender2_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property HighlightSubject2_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HighlightSubject2_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property HighlightSubject2_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HighlightSubject2_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property info_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property info_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property keyboard_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("keyboard_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Amharic
        '''Arabic
        '''Assamese
        '''Azerbaijani
        '''Bengali
        '''Bhojpuri
        '''Burmese
        '''Cantonese
        '''Cebuano
        '''Czech
        '''Dutch
        '''English
        '''French
        '''Fula
        '''Gan
        '''German
        '''Greek
        '''Gujarati
        '''Hakka
        '''Hausa
        '''Hindi
        '''Hungarian
        '''Igbo
        '''Indonesian
        '''Italian
        '''Japanese
        '''Javanese
        '''Kannada
        '''Korean
        '''Kurdish
        '''Madurese
        '''Maithili
        '''Malagasy
        '''Malay
        '''Malayalam
        '''Mandarin Chinese
        '''Marathi
        '''Min
        '''Nepali
        '''Oriya
        '''Oromo
        '''Pashto
        '''Persian
        '''Polish
        '''Portuguese
        '''Punjabi
        '''Romanian
        '''Russian
        '''Serbo-Croatian
        '''Shona
        '''Sindhi
        '''Sinhalese
        '''Spanish
        '''Sunda
        '''Tagalog
        '''Tamil
        '''Telugu
        '''Tha [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property LanguageList() As String
            Get
                Return ResourceManager.GetString("LanguageList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Message_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Message_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Message_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Message_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property MessageCopy_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MessageCopy_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property MessageCopy_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MessageCopy_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property messageforward_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("messageforward_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property MessageIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("MessageIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property messagereply_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("messagereply_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property messagereplyforward_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("messagereplyforward_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property minus_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minus_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property MsgForward_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MsgForward_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property MsgForward_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MsgForward_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property MsgReply_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MsgReply_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property MsgReply_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MsgReply_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property MsgReplyAll_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MsgReplyAll_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property MsgReplyAll_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MsgReplyAll_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property NatureMoon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NatureMoon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property network_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("network_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property network_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("network_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property NewEmail_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewEmail_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Newmessage_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Newmessage_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Newmessage_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Newmessage_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property NoImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NoImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Note_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Note_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Note_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Note_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Numbering_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Numbering_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Openmessage_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Openmessage_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Openmessage_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Openmessage_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property OtherMoney() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OtherMoney", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Paste_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Paste_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property paste2_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paste2_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property paste2_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paste2_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PauseButton_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PauseButton_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PauseButton_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PauseButton_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PeopleSmile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PeopleSmile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PlayButton_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PlayButton_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PlayButton_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PlayButton_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property plus_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plus_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Postagestamp_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Postagestamp_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Postagestamp_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Postagestamp_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Postman_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Postman_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Postman_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Postman_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Print_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Print_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Print_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Print_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property profile_female() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("profile_female", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property profile_male() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("profile_male", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Question() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Question", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property ReadMessage() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ReadMessage", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Readmessage_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Readmessage_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Readmessage_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Readmessage_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property RecordButton_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RecordButton_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property redemail_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redemail_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property redemail_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redemail_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Refresh_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Refresh_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Refresh_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Refresh_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property remove_icon_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("remove_icon_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Reply_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Reply_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property reply_3_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reply_3_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property reply_3_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reply_3_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Reply_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Reply_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property reply_all_3_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reply_all_3_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property reply_all_3_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reply_all_3_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Replytoall_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Replytoall_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Replytoall_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Replytoall_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ResumeButton_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ResumeButton_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ResumeButton_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ResumeButton_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property rss_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rss_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property rss_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rss_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Savefile_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Savefile_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Savefile_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Savefile_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Search_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Search_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Search_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Search_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property searchmessage_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("searchmessage_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property searchmessage_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("searchmessage_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property secured_email_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("secured_email_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property secured_email_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("secured_email_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Securedmessage_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Securedmessage_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Securedmessage_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Securedmessage_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Public ReadOnly Property SecuredmessageIcon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("SecuredmessageIcon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Sender_Good_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sender_Good_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Sendmail_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sendmail_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property sendmail_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sendmail_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property sendmaildelay_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sendmaildelay_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property sendmaildelay_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sendmaildelay_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Settings_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Settings_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Settings_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Settings_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ShowRemoteImageURLs_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ShowRemoteImageURLs_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property simpleX_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("simpleX_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property SpellAsYouType_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SpellAsYouType_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Spellcheck_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Spellcheck_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Spellcheck_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Spellcheck_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Stop_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stop_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Stop_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stop_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property StopButton_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StopButton_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Synchronize_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Synchronize_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Synchronize_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Synchronize_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Text_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Text_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Text_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Text_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property To_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("To_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property To_Hot_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("To_Hot_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property twitter_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("twitter_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property twitter_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("twitter_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Unlock_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Unlock_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Unlock_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Unlock_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Upload_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Upload_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Upload_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Upload_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Userprofile_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Userprofile_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Userprofile_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Userprofile_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
