'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public ReadOnly Property PortableProfile() As Boolean
            Get
                Return CType(Me("PortableProfile"),Boolean)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AutoSendReceive() As Boolean
            Get
                Return CType(Me("AutoSendReceive"),Boolean)
            End Get
            Set
                Me("AutoSendReceive") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property AutoSendReceiveInterval() As Integer
            Get
                Return CType(Me("AutoSendReceiveInterval"),Integer)
            End Get
            Set
                Me("AutoSendReceiveInterval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LogFileLocation() As String
            Get
                Return CType(Me("LogFileLocation"),String)
            End Get
            Set
                Me("LogFileLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("en-US.dct")>  _
        Public Property SpellingDictionary() As String
            Get
                Return CType(Me("SpellingDictionary"),String)
            End Get
            Set
                Me("SpellingDictionary") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SpellCheckBeforeSend() As Boolean
            Get
                Return CType(Me("SpellCheckBeforeSend"),Boolean)
            End Get
            Set
                Me("SpellCheckBeforeSend") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SendAndReceiveOnStartup() As Boolean
            Get
                Return CType(Me("SendAndReceiveOnStartup"),Boolean)
            End Get
            Set
                Me("SendAndReceiveOnStartup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property LargeToolbarIcons() As Boolean
            Get
                Return CType(Me("LargeToolbarIcons"),Boolean)
            End Get
            Set
                Me("LargeToolbarIcons") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SpellCheckSubject() As Boolean
            Get
                Return CType(Me("SpellCheckSubject"),Boolean)
            End Get
            Set
                Me("SpellCheckSubject") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AutoSaveDrafts() As Boolean
            Get
                Return CType(Me("AutoSaveDrafts"),Boolean)
            End Get
            Set
                Me("AutoSaveDrafts") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property AutoSaveDraftsMinutes() As Integer
            Get
                Return CType(Me("AutoSaveDraftsMinutes"),Integer)
            End Get
            Set
                Me("AutoSaveDraftsMinutes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("(no subject)")>  _
        Public Property DefaultMessageSubject() As String
            Get
                Return CType(Me("DefaultMessageSubject"),String)
            End Get
            Set
                Me("DefaultMessageSubject") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property AddressBookWindowState() As Integer
            Get
                Return CType(Me("AddressBookWindowState"),Integer)
            End Get
            Set
                Me("AddressBookWindowState") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property MainFormWindowState() As Integer
            Get
                Return CType(Me("MainFormWindowState"),Integer)
            End Get
            Set
                Me("MainFormWindowState") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property NewMessageWindowState() As Integer
            Get
                Return CType(Me("NewMessageWindowState"),Integer)
            End Get
            Set
                Me("NewMessageWindowState") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property OptionsFormWindowState() As Integer
            Get
                Return CType(Me("OptionsFormWindowState"),Integer)
            End Get
            Set
                Me("OptionsFormWindowState") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ReadMessageWindowState() As Integer
            Get
                Return CType(Me("ReadMessageWindowState"),Integer)
            End Get
            Set
                Me("ReadMessageWindowState") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ResendMessagesWindowState() As Integer
            Get
                Return CType(Me("ResendMessagesWindowState"),Integer)
            End Get
            Set
                Me("ResendMessagesWindowState") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SearchFormWindowState() As Integer
            Get
                Return CType(Me("SearchFormWindowState"),Integer)
            End Get
            Set
                Me("SearchFormWindowState") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EmailAutoAddRecipientsOnSend() As Boolean
            Get
                Return CType(Me("EmailAutoAddRecipientsOnSend"),Boolean)
            End Get
            Set
                Me("EmailAutoAddRecipientsOnSend") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EmailShowSenderAsSent() As Boolean
            Get
                Return CType(Me("EmailShowSenderAsSent"),Boolean)
            End Get
            Set
                Me("EmailShowSenderAsSent") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SendNowDelay() As Integer
            Get
                Return CType(Me("SendNowDelay"),Integer)
            End Get
            Set
                Me("SendNowDelay") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SendNowOnExit() As Boolean
            Get
                Return CType(Me("SendNowOnExit"),Boolean)
            End Get
            Set
                Me("SendNowOnExit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ReplyPostingMode() As Integer
            Get
                Return CType(Me("ReplyPostingMode"),Integer)
            End Get
            Set
                Me("ReplyPostingMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EmailRequestReturnReceipt() As Boolean
            Get
                Return CType(Me("EmailRequestReturnReceipt"),Boolean)
            End Get
            Set
                Me("EmailRequestReturnReceipt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property BlockRemoteImages() As Boolean
            Get
                Return CType(Me("BlockRemoteImages"),Boolean)
            End Get
            Set
                Me("BlockRemoteImages") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EnableLogging() As Boolean
            Get
                Return CType(Me("EnableLogging"),Boolean)
            End Get
            Set
                Me("EnableLogging") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DoNotShowEmailRecipientNotEncrypted() As Boolean
            Get
                Return CType(Me("DoNotShowEmailRecipientNotEncrypted"),Boolean)
            End Get
            Set
                Me("DoNotShowEmailRecipientNotEncrypted") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("15")>  _
        Public Property DelayMinutesWhenCannotSend() As Integer
            Get
                Return CType(Me("DelayMinutesWhenCannotSend"),Integer)
            End Get
            Set
                Me("DelayMinutesWhenCannotSend") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DoNotShowEmailRecipientNoReply() As Boolean
            Get
                Return CType(Me("DoNotShowEmailRecipientNoReply"),Boolean)
            End Get
            Set
                Me("DoNotShowEmailRecipientNoReply") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("15")>  _
        Public Property TrashDaysToRetain() As Integer
            Get
                Return CType(Me("TrashDaysToRetain"),Integer)
            End Get
            Set
                Me("TrashDaysToRetain") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AutoEmptyTrash() As Boolean
            Get
                Return CType(Me("AutoEmptyTrash"),Boolean)
            End Get
            Set
                Me("AutoEmptyTrash") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DoNotShowReadReceiptWillNotBeRequested() As Boolean
            Get
                Return CType(Me("DoNotShowReadReceiptWillNotBeRequested"),Boolean)
            End Get
            Set
                Me("DoNotShowReadReceiptWillNotBeRequested") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DoNotProcessEmailReceipts() As Boolean
            Get
                Return CType(Me("DoNotProcessEmailReceipts"),Boolean)
            End Get
            Set
                Me("DoNotProcessEmailReceipts") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Times New Roman")>  _
        Public Property DefaultNewMessageFontName() As String
            Get
                Return CType(Me("DefaultNewMessageFontName"),String)
            End Get
            Set
                Me("DefaultNewMessageFontName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property DefaultNewMessageFontSize() As Integer
            Get
                Return CType(Me("DefaultNewMessageFontSize"),Integer)
            End Get
            Set
                Me("DefaultNewMessageFontSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property NewMessageBackgroundColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("NewMessageBackgroundColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("NewMessageBackgroundColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ShowMessagePreviewPane() As Boolean
            Get
                Return CType(Me("ShowMessagePreviewPane"),Boolean)
            End Get
            Set
                Me("ShowMessagePreviewPane") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property MessagePreviewPaneVertical() As Boolean
            Get
                Return CType(Me("MessagePreviewPaneVertical"),Boolean)
            End Get
            Set
                Me("MessagePreviewPaneVertical") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property MessagePreviewPaneSize() As Integer
            Get
                Return CType(Me("MessagePreviewPaneSize"),Integer)
            End Get
            Set
                Me("MessagePreviewPaneSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2000-01-01")>  _
        Public Property IndexResetDate() As Date
            Get
                Return CType(Me("IndexResetDate"),Date)
            End Get
            Set
                Me("IndexResetDate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("AAEAAAD/////AQAAAAAAAAAMAgAAAEBUcnVseU1haWwsIFZlcnNpb249MS4wLjAuMCwgQ3VsdHVyZT1uZ"& _ 
            "XV0cmFsLCBQdWJsaWNLZXlUb2tlbj1udWxsDAMAAABXU3lzdGVtLldpbmRvd3MuRm9ybXMsIFZlcnNpb"& _ 
            "249Mi4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5B"& _ 
            "QEAAAA2QnJpZ2h0SWRlYXNTb2Z0d2FyZS5PYmplY3RMaXN0VmlldytPYmplY3RMaXN0Vmlld1N0YXRlC"& _ 
            "QAAAA1WZXJzaW9uTnVtYmVyD051bWJlck9mQ29sdW1ucwtDdXJyZW50VmlldwpTb3J0Q29sdW1uD0lzU"& _ 
            "2hvd2luZ0dyb3Vwcw1MYXN0U29ydE9yZGVyD0NvbHVtbklzVmlzaWJsZRVDb2x1bW5EaXNwbGF5SW5ka"& _ 
            "WNpZXMMQ29sdW1uV2lkdGhzAAAEAAAEAwMDCAgZU3lzdGVtLldpbmRvd3MuRm9ybXMuVmlldwMAAAAIA"& _ 
            "R5TeXN0ZW0uV2luZG93cy5Gb3Jtcy5Tb3J0T3JkZXIDAAAAHFN5c3RlbS5Db2xsZWN0aW9ucy5BcnJhe"& _ 
            "Uxpc3QcU3lzdGVtLkNvbGxlY3Rpb25zLkFycmF5TGlzdBxTeXN0ZW0uQ29sbGVjdGlvbnMuQXJyYXlMa"& _ 
            "XN0AgAAAAEAAAALAAAABfz///8ZU3lzdGVtLldpbmRvd3MuRm9ybXMuVmlldwEAAAAHdmFsdWVfXwAIA"& _ 
            "wAAAAEAAAADAAAAAAX7////HlN5c3RlbS5XaW5kb3dzLkZvcm1zLlNvcnRPcmRlcgEAAAAHdmFsdWVfX"& _ 
            "wAIAwAAAAIAAAAJBgAAAAkHAAAACQgAAAAEBgAAABxTeXN0ZW0uQ29sbGVjdGlvbnMuQXJyYXlMaXN0A"& _ 
            "wAAAAZfaXRlbXMFX3NpemUIX3ZlcnNpb24FAAAICAkJAAAACwAAAAsAAAABBwAAAAYAAAAJCgAAAAsAA"& _ 
            "AALAAAAAQgAAAAGAAAACQsAAAALAAAACwAAABAJAAAAEAAAAAgBAQgBAQgBAQgBAQgBAQgBAQgBAQgBA"& _ 
            "QgBAQgBAQgBAQ0FEAoAAAAQAAAACAgCAAAACAgDAAAACAgEAAAACAgFAAAACAgGAAAACAgHAAAACAgIA"& _ 
            "AAACAgAAAAACAgBAAAACAgJAAAACAgKAAAADQUQCwAAABAAAAAICGQBAAAICBkAAAAICIcAAAAICIgAA"& _ 
            "AAICDcAAAAICCMAAAAICCgAAAAICBkAAAAICBkAAAAICEIAAAAICGYAAAANBQs=")>  _
        Public Property MessageListState() As String
            Get
                Return CType(Me("MessageListState"),String)
            End Get
            Set
                Me("MessageListState") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SingleSpaceEditor() As Boolean
            Get
                Return CType(Me("SingleSpaceEditor"),Boolean)
            End Get
            Set
                Me("SingleSpaceEditor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShowEditorSpacingStatus() As Boolean
            Get
                Return CType(Me("ShowEditorSpacingStatus"),Boolean)
            End Get
            Set
                Me("ShowEditorSpacingStatus") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.6")>  _
        Public Property MessagePreviewLoadDelay() As Decimal
            Get
                Return CType(Me("MessagePreviewLoadDelay"),Decimal)
            End Get
            Set
                Me("MessagePreviewLoadDelay") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DoNotShowReplyAllBCCNotice() As Boolean
            Get
                Return CType(Me("DoNotShowReplyAllBCCNotice"),Boolean)
            End Get
            Set
                Me("DoNotShowReplyAllBCCNotice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShowReminderAreaNewMessage() As Boolean
            Get
                Return CType(Me("ShowReminderAreaNewMessage"),Boolean)
            End Get
            Set
                Me("ShowReminderAreaNewMessage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EmptyTrashOnExit() As Boolean
            Get
                Return CType(Me("EmptyTrashOnExit"),Boolean)
            End Get
            Set
                Me("EmptyTrashOnExit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DoNotShowAddEmailAccountNotice() As Boolean
            Get
                Return CType(Me("DoNotShowAddEmailAccountNotice"),Boolean)
            End Get
            Set
                Me("DoNotShowAddEmailAccountNotice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DoNotShowBlockedScriptsNotice() As Boolean
            Get
                Return CType(Me("DoNotShowBlockedScriptsNotice"),Boolean)
            End Get
            Set
                Me("DoNotShowBlockedScriptsNotice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property AddressBookListState() As String
            Get
                Return CType(Me("AddressBookListState"),String)
            End Get
            Set
                Me("AddressBookListState") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2000-01-01")>  _
        Public Property ContactLastSentUpdated() As Date
            Get
                Return CType(Me("ContactLastSentUpdated"),Date)
            End Get
            Set
                Me("ContactLastSentUpdated") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AutoSpellCheckNewMessage() As Boolean
            Get
                Return CType(Me("AutoSpellCheckNewMessage"),Boolean)
            End Get
            Set
                Me("AutoSpellCheckNewMessage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DoNotShowRemovedRecipientNotice() As Boolean
            Get
                Return CType(Me("DoNotShowRemovedRecipientNotice"),Boolean)
            End Get
            Set
                Me("DoNotShowRemovedRecipientNotice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MinimizeToTray() As Boolean
            Get
                Return CType(Me("MinimizeToTray"),Boolean)
            End Get
            Set
                Me("MinimizeToTray") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShowNoticeForNewMessages() As Boolean
            Get
                Return CType(Me("ShowNoticeForNewMessages"),Boolean)
            End Get
            Set
                Me("ShowNoticeForNewMessages") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Default")>  _
        Public Property NewMessageNotifySound() As String
            Get
                Return CType(Me("NewMessageNotifySound"),String)
            End Get
            Set
                Me("NewMessageNotifySound") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property KeepSentMessages() As Boolean
            Get
                Return CType(Me("KeepSentMessages"),Boolean)
            End Get
            Set
                Me("KeepSentMessages") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ImageResizePromptFrequency() As Integer
            Get
                Return CType(Me("ImageResizePromptFrequency"),Integer)
            End Get
            Set
                Me("ImageResizePromptFrequency") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ImageResizeSize() As Integer
            Get
                Return CType(Me("ImageResizeSize"),Integer)
            End Get
            Set
                Me("ImageResizeSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ReadMessageHeaderCompactMode() As Boolean
            Get
                Return CType(Me("ReadMessageHeaderCompactMode"),Boolean)
            End Get
            Set
                Me("ReadMessageHeaderCompactMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ToolBarsShowText() As Boolean
            Get
                Return CType(Me("ToolBarsShowText"),Boolean)
            End Get
            Set
                Me("ToolBarsShowText") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property EncryptionVersion() As Integer
            Get
                Return CType(Me("EncryptionVersion"),Integer)
            End Get
            Set
                Me("EncryptionVersion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UseLargeAllAccountDropDown() As Boolean
            Get
                Return CType(Me("UseLargeAllAccountDropDown"),Boolean)
            End Get
            Set
                Me("UseLargeAllAccountDropDown") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MaintainMessageZoom() As Boolean
            Get
                Return CType(Me("MaintainMessageZoom"),Boolean)
            End Get
            Set
                Me("MaintainMessageZoom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property TextTagButtons() As Boolean
            Get
                Return CType(Me("TextTagButtons"),Boolean)
            End Get
            Set
                Me("TextTagButtons") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CountOfDictionariesAvailable() As Integer
            Get
                Return CType(Me("CountOfDictionariesAvailable"),Integer)
            End Get
            Set
                Me("CountOfDictionariesAvailable") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DefaultEmailEncryption() As Integer
            Get
                Return CType(Me("DefaultEmailEncryption"),Integer)
            End Get
            Set
                Me("DefaultEmailEncryption") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DoNotShowDecryptedBodyOverwriteWarning() As Boolean
            Get
                Return CType(Me("DoNotShowDecryptedBodyOverwriteWarning"),Boolean)
            End Get
            Set
                Me("DoNotShowDecryptedBodyOverwriteWarning") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MainFormFilterAutoComplete() As String
            Get
                Return CType(Me("MainFormFilterAutoComplete"),String)
            End Get
            Set
                Me("MainFormFilterAutoComplete") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DoNotShowBlockedIFramesNotice() As Boolean
            Get
                Return CType(Me("DoNotShowBlockedIFramesNotice"),Boolean)
            End Get
            Set
                Me("DoNotShowBlockedIFramesNotice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DoNotShowTipPanel() As Boolean
            Get
                Return CType(Me("DoNotShowTipPanel"),Boolean)
            End Get
            Set
                Me("DoNotShowTipPanel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("150")>  _
        Public Property ContactInfoAreaSplitter() As Integer
            Get
                Return CType(Me("ContactInfoAreaSplitter"),Integer)
            End Get
            Set
                Me("ContactInfoAreaSplitter") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShowReadingZoomBar() As Boolean
            Get
                Return CType(Me("ShowReadingZoomBar"),Boolean)
            End Get
            Set
                Me("ShowReadingZoomBar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property NoticeForNewMessagesSecondsOpen() As Decimal
            Get
                Return CType(Me("NoticeForNewMessagesSecondsOpen"),Decimal)
            End Get
            Set
                Me("NoticeForNewMessagesSecondsOpen") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property MainWindowLocationX() As Integer
            Get
                Return CType(Me("MainWindowLocationX"),Integer)
            End Get
            Set
                Me("MainWindowLocationX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property MainWindowLocationY() As Integer
            Get
                Return CType(Me("MainWindowLocationY"),Integer)
            End Get
            Set
                Me("MainWindowLocationY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1024")>  _
        Public Property MainWindowSizeWidth() As Integer
            Get
                Return CType(Me("MainWindowSizeWidth"),Integer)
            End Get
            Set
                Me("MainWindowSizeWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("570")>  _
        Public Property MainWindowSizeHeight() As Integer
            Get
                Return CType(Me("MainWindowSizeHeight"),Integer)
            End Get
            Set
                Me("MainWindowSizeHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ReadWindowLocationX() As Integer
            Get
                Return CType(Me("ReadWindowLocationX"),Integer)
            End Get
            Set
                Me("ReadWindowLocationX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ReadWindowLocationY() As Integer
            Get
                Return CType(Me("ReadWindowLocationY"),Integer)
            End Get
            Set
                Me("ReadWindowLocationY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("850")>  _
        Public Property ReadWindowSizeWidth() As Integer
            Get
                Return CType(Me("ReadWindowSizeWidth"),Integer)
            End Get
            Set
                Me("ReadWindowSizeWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("700")>  _
        Public Property ReadWindowSizeHeight() As Integer
            Get
                Return CType(Me("ReadWindowSizeHeight"),Integer)
            End Get
            Set
                Me("ReadWindowSizeHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ComposeWindowLocationX() As Integer
            Get
                Return CType(Me("ComposeWindowLocationX"),Integer)
            End Get
            Set
                Me("ComposeWindowLocationX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ComposeWindowLocationY() As Integer
            Get
                Return CType(Me("ComposeWindowLocationY"),Integer)
            End Get
            Set
                Me("ComposeWindowLocationY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("995")>  _
        Public Property ComposeWindowSizeWidth() As Integer
            Get
                Return CType(Me("ComposeWindowSizeWidth"),Integer)
            End Get
            Set
                Me("ComposeWindowSizeWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("595")>  _
        Public Property ComposeWindowSizeHeight() As Integer
            Get
                Return CType(Me("ComposeWindowSizeHeight"),Integer)
            End Get
            Set
                Me("ComposeWindowSizeHeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShowAutoTextComposeWindow() As Boolean
            Get
                Return CType(Me("ShowAutoTextComposeWindow"),Boolean)
            End Get
            Set
                Me("ShowAutoTextComposeWindow") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property EditorCustomColors() As String
            Get
                Return CType(Me("EditorCustomColors"),String)
            End Get
            Set
                Me("EditorCustomColors") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("150")>  _
        Public Property ComposeAutoTextAreaSplitter() As Integer
            Get
                Return CType(Me("ComposeAutoTextAreaSplitter"),Integer)
            End Get
            Set
                Me("ComposeAutoTextAreaSplitter") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DateFormat() As Integer
            Get
                Return CType(Me("DateFormat"),Integer)
            End Get
            Set
                Me("DateFormat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EmailAutoAddRecipientsTieSMTP() As Boolean
            Get
                Return CType(Me("EmailAutoAddRecipientsTieSMTP"),Boolean)
            End Get
            Set
                Me("EmailAutoAddRecipientsTieSMTP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property RSSAutoCheckAtStartup() As Boolean
            Get
                Return CType(Me("RSSAutoCheckAtStartup"),Boolean)
            End Get
            Set
                Me("RSSAutoCheckAtStartup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property RSSAutoCheckInterval() As Integer
            Get
                Return CType(Me("RSSAutoCheckInterval"),Integer)
            End Get
            Set
                Me("RSSAutoCheckInterval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property RSSAutoCheck() As Boolean
            Get
                Return CType(Me("RSSAutoCheck"),Boolean)
            End Get
            Set
                Me("RSSAutoCheck") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("188")>  _
        Public Property FolderTreeSplitter() As Integer
            Get
                Return CType(Me("FolderTreeSplitter"),Integer)
            End Get
            Set
                Me("FolderTreeSplitter") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DoNotShowPOP3DownloadErrorNotice() As Boolean
            Get
                Return CType(Me("DoNotShowPOP3DownloadErrorNotice"),Boolean)
            End Get
            Set
                Me("DoNotShowPOP3DownloadErrorNotice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DoNotShowReadMessageBlockNotice() As Boolean
            Get
                Return CType(Me("DoNotShowReadMessageBlockNotice"),Boolean)
            End Get
            Set
                Me("DoNotShowReadMessageBlockNotice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DoNotShowMissingSubjectNotice() As Boolean
            Get
                Return CType(Me("DoNotShowMissingSubjectNotice"),Boolean)
            End Get
            Set
                Me("DoNotShowMissingSubjectNotice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DoNotShowShutDownErrorNotice() As Boolean
            Get
                Return CType(Me("DoNotShowShutDownErrorNotice"),Boolean)
            End Get
            Set
                Me("DoNotShowShutDownErrorNotice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("To read the contents of this file, you will need a zip utility which supports AES"& _ 
            "256 encrypted zip files (like WinZip, 7-Zip, WinRar, etc.)")>  _
        Public Property WebMessageAttachmentComment() As String
            Get
                Return CType(Me("WebMessageAttachmentComment"),String)
            End Get
            Set
                Me("WebMessageAttachmentComment") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ReplyToPlainTextIsPlainText() As Boolean
            Get
                Return CType(Me("ReplyToPlainTextIsPlainText"),Boolean)
            End Get
            Set
                Me("ReplyToPlainTextIsPlainText") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("InBox")>  _
        Public Property WebPageMonitorInbox() As String
            Get
                Return CType(Me("WebPageMonitorInbox"),String)
            End Get
            Set
                Me("WebPageMonitorInbox") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Georgia")>  _
        Public Property PlainTextFontName() As String
            Get
                Return CType(Me("PlainTextFontName"),String)
            End Get
            Set
                Me("PlainTextFontName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("12")>  _
        Public Property PlainTextFontSize() As Integer
            Get
                Return CType(Me("PlainTextFontSize"),Integer)
            End Get
            Set
                Me("PlainTextFontSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AutoZipEmailAttachments() As Boolean
            Get
                Return CType(Me("AutoZipEmailAttachments"),Boolean)
            End Get
            Set
                Me("AutoZipEmailAttachments") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MessageExportFolder() As String
            Get
                Return CType(Me("MessageExportFolder"),String)
            End Get
            Set
                Me("MessageExportFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MessageExportTrulyMailFakeAddress() As String
            Get
                Return CType(Me("MessageExportTrulyMailFakeAddress"),String)
            End Get
            Set
                Me("MessageExportTrulyMailFakeAddress") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MasterPasswordHashLong() As String
            Get
                Return CType(Me("MasterPasswordHashLong"),String)
            End Get
            Set
                Me("MasterPasswordHashLong") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DoNotShowSMTPServerConnectionTimeOutErrorNotice() As Boolean
            Get
                Return CType(Me("DoNotShowSMTPServerConnectionTimeOutErrorNotice"),Boolean)
            End Get
            Set
                Me("DoNotShowSMTPServerConnectionTimeOutErrorNotice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DoNotShowPOPServerConnectionTimeOutErrorNotice() As Boolean
            Get
                Return CType(Me("DoNotShowPOPServerConnectionTimeOutErrorNotice"),Boolean)
            End Get
            Set
                Me("DoNotShowPOPServerConnectionTimeOutErrorNotice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property IntraEmailSendDelay() As Integer
            Get
                Return CType(Me("IntraEmailSendDelay"),Integer)
            End Get
            Set
                Me("IntraEmailSendDelay") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.TrulyMail.My.MySettings
            Get
                Return Global.TrulyMail.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
